######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 31 08:55:43 2009
######################################################################

include(../common.pri)

TEMPLATE = app
TARGET = memoryhog
DEPENDPATH += .
INCLUDEPATH += .

QT =
LIBS =

# Input
SOURCES += memoryhog.c


